title: Default Page

columns:
  main:
    width: 2/3
    fields:
      text:
        label: Text
        type: textarea
  sidebar:
    width: 1/3
    fields:
      downloads:
        label: Verknüpfte Dateien
        type: files
      toggle:
        label: Toggle
        type: toggle
        text: Sidebar anzeigen?
      sidebar:
        label: Links
        type: structure
        fields:
          link:
            label: URL
            type: url
          name:
            label: Bezeichnung
            type: text