title: KGS Rastede

tabs:
  alles:
    label: Inhalte
    preset: pages
    unlisted: true

  einstellungen:
    label: Einstellungen
    icon: settings
    sections:
      banner:
        type: fields
        fields:
          bannerhinweis:
            type: info
            text: Hintergrundbilder für den Startseiten-Header. Das passende Bild wird automatisch je nach Tageszeit gewählt.
          bildmorgens:
            label: Morgens (Sonnenaufgang bis Zenit)
            type: files
            multiple: false
            layout: cards
            uploads: hintergrundbild
          bildtag:
            label: Mittags (Zenit bis Sonnenuntergang)
            type: files
            multiple: false
            layout: cards
            uploads: hintergrundbild
          bildnacht:
            label: Nachts (Sonnenuntergang bis Sonnenaufgang)
            type: files
            multiple: false
            layout: cards
            uploads: hintergrundbild
          bildregen:
            label: Fallback-Bild
            type: files
            multiple: false
            layout: cards
            uploads: hintergrundbild
      seo:
        type: fields
        fields:
          description:
            label: Standard-Meta-Beschreibung
            type: textarea
            rows: 3
            help: Wird auf allen Seiten verwendet, die keine eigene Meta-Beschreibung haben

  # Lesezeichen
  bookmark:
    label: Lesezeichen
    icon: bookmark
    sections:
      seiten:
        type: fields
        fields:
          pages:
