title: KGS Rastede

tabs:
  alles:
    label: Inhalte
    preset: pages
    unlisted: true

  einstellungen:
    label: Einstellungen
    icon: settings
    sections:
      banner:
        type: fields
        fields:
          bannerueberschrift:
            type: headline
            label: Hintergrundbilder (Startseite)
          bannerhinweis:
            type: info
            text: "Die Hintergrundbilder der Startseite werden auf der Seite (link: /panel/pages/design text: Bilder auf der Seite) gepflegt."
      seo:
        type: fields
        fields:
          seoueberschrift:
            type: headline
            label: Suchmaschinenoptimierung (SEO)
          description:
            label: Standard-Meta-Beschreibung
            type: textarea
            rows: 3
            help: Wird auf allen Seiten verwendet, die keine eigene Meta-Beschreibung haben

  # Lesezeichen
  bookmark:
    label: Lesezeichen
    icon: bookmark
    sections:
      seiten:
        type: fields
        fields:
          pages:
